services:
    bot:
        container_name: mc_bot #! change this
        image: node:slim
        volumes:
            - ./bot/:/bot/
            - ./package.json:/bot/package.json
            - ./package-lock.json:/bot/package-lock.json
            - ./src/config.json:/bot/config.json
        working_dir: /bot
        entrypoint: /bot/entrypoint.sh
        network_mode: "host"
        extra_hosts:
            - "host.docker.internal:host-gateway"
